<a href="https://colab.research.google.com/github/NairSailesh/GO_STP_342/blob/main/STP_Task04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


2. Create a null vector of size 10

In [3]:
ten = np.zeros(10)
print(ten)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create Simple 1-D array and check type and check data types in array

In [4]:
d = np.array([1,2,3,4,5,6])
print(d)
print(type(d))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
d.dtype

dtype('int64')

4. How to find number of dimensions, bytes per element and bytes of memory used?

In [6]:
print('Dimensions: ',d.shape)
print("Size of one element in bytes: ",d.itemsize)
print("Size of the array: ",d.size*d.itemsize)  


Dimensions:  (6,)
Size of one element in bytes:  8
Size of the array:  48


5. Create a null vector of size 10 but the fifth value which is 1

In [7]:
a=(np.arange(10)==4).astype(int)
print(a)

[0 0 0 0 1 0 0 0 0 0]


6. Create a vector with values ranging from 10 to 49

In [8]:
v6=np.arange(10,49)
print(v6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


7. Reverse a vector (first element becomes last)

In [9]:
np.flip(v6)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

8. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
m=np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
f = [1,2,0,0,4,0]
np.nonzero(f)

(array([0, 1, 4]),)

10. Create a 3x3 identity matrix

In [12]:
o=np.ones((3,3)).astype(int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


 11. Create a 3x3x3 array with random values

In [13]:
r=np.random.randint(10,90,(3,3,3))
print(r)

[[[57 24 64]
  [35 22 11]
  [62 82 50]]

 [[78 56 79]
  [83 87 87]
  [50 83 64]]

 [[31 31 75]
  [50 69 44]
  [79 56 52]]]


12. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
x = np.random.randint(100,900,(10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[627 684 653 174 189 333 424 620 436 738]
 [824 808 360 114 355 799 520 734 452 545]
 [135 377 265 665 715 669 169 728 580 779]
 [564 262 888 201 828 465 831 593 119 259]
 [301 809 151 307 651 206 783 690 675 178]
 [687 417 641 619 226 791 548 352 372 847]
 [138 194 244 186 121 439 383 893 391 128]
 [766 659 654 103 800 150 322 817 504 625]
 [617 697 611 242 373 740 170 559 727 838]
 [456 578 379 203 764 277 331 147 740 896]]
Minimum and Maximum Values:
103 896


13. Create a random vector of size 30 and find the mean value

In [15]:
x = np.random.randint(100,900,(10))
print(x)
print('Mean:',x.mean())

[169 379 846 294 386 117 375 689 266 113]
Mean: 363.4


14. Create a 2d array with 1 on the border and 0 inside

In [16]:
x=np.ones((3,3))
print(x)
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


15. How to add a border (filled with 0's) around an existing array? 

In [17]:
x=np.ones((3,3))
print(x)
y=np.pad(x,1,mode='constant',constant_values=0)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [18]:
m=np.arange(1,15).reshape(2,7)
print(m)
print('Get 13',m[1,-2])
print('get first row only',m[0,])
print('get 3rd column only\n',m[:,[2]])
print('get [2, 4, 6],\n',m[0,][1::2])
m[1,-2]=20
print('replace 13 by 20')
m

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Get 13 13
get first row only [1 2 3 4 5 6 7]
get 3rd column only
 [[ 3]
 [10]]
get [2, 4, 6],
 [2 4 6]
replace 13 by 20


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

17. How to Convert a 1D array to a 2D array with 2 rows

In [19]:
m1d=np.array( [ 1,  2,  3,  4,  5,  6,])
print('1d array : \n',m1d)
m2d = m1d.reshape(3,2)
print('2d array : \n',m2d)


1d array : 
 [1 2 3 4 5 6]
2d array : 
 [[1 2]
 [3 4]
 [5 6]]


18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])
Desired Output:

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
a = np.array([1,2,3])
print(np.concatenate((np.repeat(a,3),np.tile(a,3))))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


19. Write a program to show how Numpy taking less memory compared to Python List?

In [21]:
import sys

array = np.arange(100)
print("Size of NumPy array: ", array.itemsize * array.itemsize)

list = range(0, 10)
print("Size of list: ", sys.getsizeof(1)*len(list))

Size of NumPy array:  64
Size of list:  280


NumPy array consumes less memory as compared to the Python list.

20. Write a program to show how Numpy taking less time compared to Python List?

In [22]:
import time
import sys

Size = 100000

list1 = range(Size)
list2 = range(Size)

arr1 = np.arange(Size)
arr2 = np.arange(Size)

start = time.time()
result = [(x*y) for x, y in zip(list1, list2)]        
print("Time for Python List in msec: ", (time.time() - start) * 1000)

start = time.time()
result = arr1*arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)


Time for Python List in msec:  11.963129043579102
Time for NumPy array in msec:  2.0363330841064453
